name: Release on tag

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Get tag version
      id: tag
      shell: bash
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - uses: actions/checkout@v2.3.4

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x

    - name: Publish with dotnet
      run: dotnet publish GenshinLyreMidiPlayer.WPF -r win-x64 -c Release -o .\output --self-contained false -p:PublishSingleFile=true

    - name: Zip release
      run: 7z a GenshinLyreMidiPlayer_${{ steps.tag.outputs.VERSION }}_win-x64.zip .\output\* -x!*.pdb

    - name: 7Zip release
      run: 7z a GenshinLyreMidiPlayer_${{ steps.tag.outputs.VERSION }}_win-x64.7z .\output\* -x!*.pdb

    - name: Create Release
      uses: ncipollo/release-action@v1.8.4
      with:
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          artifacts: ./GenshinLyreMidiPlayer_${{ steps.tag.outputs.VERSION }}_win-x64.zip,./GenshinLyreMidiPlayer_${{ steps.tag.outputs.VERSION }}_win-x64.7z
          artifactContentType: application/zip
          token: ${{ secrets.GITHUB_TOKEN }}