name: Release on tag

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
          runtime: ["win-x64", "win-x86"]

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x

    - name: Publish with dotnet
      run: dotnet publish GenshinLyreMidiPlayer.WPF -r ${{ matrix.runtime }} -c Release -o .\output --self-contained false -p:PublishSingleFile=true

    - name: Zip artifacts
      run: 7z a ${{ matrix.runtime }}.zip .\output\*

    - name: Create Release
      uses: ncipollo/release-action@v1.8.4
      with:
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          artifacts: ./${{ matrix.runtime }}.zip
          artifactContentType: application/zip
          token: ${{ secrets.GITHUB_TOKEN }}